[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 16

[font.bold]
family = "DejaVuSansMono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansMono"
style = "Bold Oblique"

[font.italic]
family = "DejaVuSansMono"
style = "Oblique"

[font.normal]
family = "DejaVuSansMono"
style = "Book"

[font.offset]
x = -1
y = 1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 16
y = 16

[terminal]
